spring:
  application:
    name: job_find_consumer
  kafka:
    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVER}
email: # send grid
  key: ${SENDGRID_API_KEY}
  mail: ${SENDGRID_EMAIL}
  link:
    register: templates/register-email.html
